### ISSUE TITLE
BulldogComponentTest causes JVM to crash on BeagleBoneBlack

### ISSUE THREAD

**Issue by sbunciak** [px3/bulldog#51]
Running on BBB, Debian Jessie, gcc-4.8, Oracle JDK 1.8.
Note: running without root permissions, however the same test fails properly on raspberrypi.

```
Running io.silverspoon.BulldogComponentTest
[                          main] BulldogComponentTest           INFO  ********************************************************************************
[                          main] BulldogComponentTest           INFO  Testing: testGpio(io.silverspoon.BulldogComponentTest)
[                          main] BulldogComponentTest           INFO  ********************************************************************************
[                          main] DefaultTypeConverter           INFO  Loaded 182 type converters
[                          main] DefaultCamelContext            INFO  Apache Camel 2.15.1 (CamelContext: camel-1) is starting
[                          main] DefaultCamelContext            INFO  Debugger: DefaultDebugger is enabled on CamelContext: camel-1
[                          main] DefaultManagementStrategy      INFO  JMX is disabled
java.lang.ArrayIndexOutOfBoundsException: 0
	at io.silverspoon.bulldog.beagleboneblack.sysfs.BBBSysFs.getCapeManager(Unknown Source)
	at io.silverspoon.bulldog.beagleboneblack.sysfs.BBBSysFs.getCapeManagerSlots(Unknown Source)
	at io.silverspoon.bulldog.beagleboneblack.sysfs.BBBSysFs.readSlots(Unknown Source)
	at io.silverspoon.bulldog.beagleboneblack.sysfs.BBBSysFs.getSlotNumber(Unknown Source)
	at io.silverspoon.bulldog.beagleboneblack.BeagleBoneBlack.isHdmiEnabled(Unknown Source)
	at io.silverspoon.bulldog.beagleboneblack.BeagleBoneBlack.createPins(Unknown Source)
	at io.silverspoon.bulldog.beagleboneblack.BeagleBoneBlack.<init>(Unknown Source)
	at io.silverspoon.bulldog.beagleboneblack.BeagleBoneBlackBoardFactory.createBoard(Unknown Source)
	at io.silverspoon.bulldog.core.platform.Platform.createBoard(Unknown Source)
	at io.silverspoon.BulldogEndpoint.<init>(BulldogEndpoint.java:50)
	at io.silverspoon.BulldogComponent.createEndpoint(BulldogComponent.java:44)
```

...

```
# A fatal error has been detected by the Java Runtime Environment:
#
SUREFIRE-859: #  SIGSEGV (0xb) at pc=0xab82cb50, pid=14763, tid=3057665120
#
# JRE version: Java(TM) SE Runtime Environment (8.0_51-b07) (build 1.8.0_51-b07)
# Java VM: Java HotSpot(TM) Client VM (25.51-b07 mixed mode linux-arm )
# Problematic frame:
# C  [bulldog-linux-native1397593381998999446.so+0x4b50]  BBBIO_sys_Enable_GPIO+0x33
#
SUREFIRE-859: # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/debian/workspace/silverspoon/label/beaglebone/silverspoon/camel-bulldog/hs_err_pid14763.log
#
SUREFIRE-859: # If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
SUREFIRE-859: iolib_init: CM_PER mmap failure! ,error :Bad file descriptor
```

Full log: http://pastebin.com/id6tRLUb

**Comment by mpbarnwell** [comment]
Anyone had chance to look at the pull request I submitted? It would be great to get a minor release of this out with current kernel support in
